<?php

// php artisan db:seed --class=QuestionSeeder

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionSeeder extends Seeder
{
    public function run()
    {
        $questions = [
            // General Information
            [
                'question' => 'What is the smallest country in the world by area?',
                'options' => json_encode(['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein']),
                'correct_option' => '1',
                'category' => 'General Information',
            ],
            [
                'question' => 'Which element has the chemical symbol O?',
                'options' => json_encode(['Oxygen', 'Osmium', 'Gold', 'Argon']),
                'correct_option' => '0',
                'category' => 'General Information',
            ],
            [
                'question' => 'What is the capital of Japan?',
                'options' => json_encode(['Tokyo', 'Osaka', 'Kyoto', 'Hiroshima']),
                'correct_option' => '0',
                'category' => 'General Information',
            ],
            [
                'question' => 'Which planet is closest to the Sun?',
                'options' => json_encode(['Venus', 'Mars', 'Earth', 'Mercury']),
                'correct_option' => '3',
                'category' => 'General Information',
            ],

            [

                'question' => 'What is the capital of Australia?',
                'options' => json_encode(['Sydney', 'Canberra', 'Melbourne', 'Brisbane']),
                'correct_option' => '1',
                'category' => 'General Information',
            ],
            [
                'question' => 'Who wrote "Romeo and Juliet"?',
                'options' => json_encode(['Charles Dickens', 'William Shakespeare', 'Mark Twain', 'Homer']),
                'correct_option' => '1',
                'category' => 'General Information',
            ],
            [
                'question' => 'What is the chemical symbol for water?',
                'options' => json_encode(['O2', 'CO2', 'H2O', 'HO']),
                'correct_option' => '2',
                'category' => 'General Information',
            ],
            [
                'question' => 'How many continents are there on Earth?',
                'options' => json_encode(['5', '6', '7', '8']),
                'correct_option' => '2',
                'category' => 'General Information',
            ],
            [
                'question' => 'What is the largest mammal in the world?',
                'options' => json_encode(['Elephant', 'Blue Whale', 'Giraffe', 'Hippopotamus']),
                'correct_option' => '1',
                'category' => 'General Information',
            ],
            [
                'question' => 'What is the primary language spoken in Brazil?',
                'options' => json_encode(['Spanish', 'English','French', 'Portuguese']),
                'correct_option' => '3',
                'category' => 'General Information',
            ],
            [
                'question' => 'Who discovered penicillin?',
                'options' => json_encode(['Marie Curie', 'Isaac Newton','Albert Einstein', 'Alexander Fleming']),
                'correct_option' => '3',
                'category' => 'General Information',
            ],
            [
                'question' => 'What is the fastest land animal?',
                'options' => json_encode(['Cheetah', 'Lion', 'Horse', 'Falcon']),
                'correct_option' => '0',
                'category' => 'General Information',
            ],
            [
                'question' => 'Which planet is closest to the sun?',
                'options' => json_encode(['Venus', 'Mercury', 'Mars', 'Earth']),
                'correct_option' => '1',
                'category' => 'General Information',
            ],
            [
                'question' => 'What year did World War II end?',
                'options' => json_encode(['1942', '1945', '1948', '1950']),
                'correct_option' => '1',
                'category' => 'General Information',
            ],
            [
                'question' => 'What is the national currency of Japan?',
                'options' => json_encode(['Yuan', 'Yen', 'Won', 'Dollar']),
                'correct_option' => '1',
                'category' => 'General Information',
            ],
            [
                'question' => 'What is the hardest natural substance on Earth?',
                'options' => json_encode(['Gold', 'Iron', 'Diamond', 'Platinum']),
                'correct_option' => '2',
                'category' => 'General Information',
            ],
            [
                'question' => 'Who painted the Mona Lisa?',
                'options' => json_encode(['Leonardo da Vinci', 'Michelangelo', 'Van Gogh', 'Raphael']),
                'correct_option' => '0',
                'category' => 'General Information',
            ],
            [
                'question' => 'What is the tallest mountain in the world?',
                'options' => json_encode(['K2', 'Mount Everest', 'Kangchenjunga', 'Makalu']),
                'correct_option' => '1',
                'category' => 'General Information',
            ],
            [
                'question' => 'Which element has the atomic number 1?',
                'options' => json_encode(['Oxygen', 'Hydrogen', 'Helium', 'Carbon']),
                'correct_option' => '1',
                'category' => 'General Information',
            ],
            [
                'question' => 'Who invented the telephone?',
                'options' => json_encode(['Alexander Graham Bell', 'Thomas Edison',  'Nikola Tesla', 'Marconi']),
                'correct_option' => '0',
                'category' => 'General Information',
            ],
            [
                'question' => 'What is the largest ocean in the world?',
                'options' => json_encode(['Atlantic Ocean', 'Indian Ocean', 'Pacific Ocean', 'Arctic Ocean']),
                'correct_option' => '2',
                'category' => 'General Information',
            ],
            [
                'question' => 'What is the smallest prime number?',
                'options' => json_encode(['1', '2', '3', '5']),
                'correct_option' => '1',
                'category' => 'General Information',
            ],
            [
                'question' => 'What is the most spoken language in the world?',
                'options' => json_encode(['English', 'Mandarin', 'Spanish', 'Hindi']),
                'correct_option' => '1',
                'category' => 'General Information',
            ],
            [
                'question' => 'What is the main ingredient in guacamole?',
                'options' => json_encode(['Tomato', 'Avocado', 'Onion', 'Lime']),
                'correct_option' => '1',
                'category' => 'General Information',
            ],
            [
                'question' => 'Which country is known as the Land of the Rising Sun?',
                'options' => json_encode(['China', 'Thailand','South Korea', 'Japan']),
                'correct_option' => '3',
                'category' => 'General Information',
            ],
            [
                'question' => 'What is the square root of 64?',
                'options' => json_encode(['6', '7', '8', '9']),
                'correct_option' => '2',
                'category' => 'General Information',
            ],
            [
                'question' => 'What is the smallest bone in the human body?',
                'options' => json_encode(['Femur', 'Ulna','Tibia', 'Stapes']),
                'correct_option' => '3',
                'category' => 'General Information',
            ],
            [
                'question' => 'Who was the first person to walk on the moon?',
                'options' => json_encode(['Buzz Aldrin', 'Neil Armstrong', 'Yuri Gagarin', 'Alan Shepard']),
                'correct_option' => '1',
                'category' => 'General Information',
            ],
            [
                'question' => 'What is the primary gas found in the Earth’s atmosphere?',
                'options' => json_encode(['Oxygen', 'Carbon Dioxide','Hydrogen', 'Nitrogen']),
                'correct_option' => '3',
                'category' => 'General Information',
            ],
            [
                'question' => 'Which country has the most Olympic gold medals?',
                'options' => json_encode(['USA', 'China', 'Russia', 'Germany']),
                'correct_option' => '0',
                'category' => 'General Information',
            ],
            [
                'question' => 'What is the first element on the periodic table?',
                'options' => json_encode(['Helium', 'Oxygen', 'Hydrogen', 'Carbon']),
                'correct_option' => '2',
                'category' => 'General Information',
            ],
            [
                'question' => 'What is the capital city of Canada?',
                'options' => json_encode(['Toronto', 'Vancouver', 'Montreal', 'Ottawa']),
                'correct_option' => '3',
                'category' => 'General Information',
            ],
            [
                'question' => 'Who was known as the Iron Lady?',
                'options' => json_encode(['Margaret Thatcher', 'Angela Merkel', 'Indira Gandhi', 'Golda Meir']),
                'correct_option' => '0',
                'category' => 'General Information',
            ],
            [
                'question' => 'What is the currency used in the United Kingdom?',
                'options' => json_encode(['Euro', 'Dollar', 'Pound Sterling', 'Franc']),
                'correct_option' => '2',
                'category' => 'General Information',
            ],



            // Coding
            [
                'question' => 'Which language is primarily used for Android development?',
                'options' => json_encode(['Swift', 'Python', 'Kotlin', 'Ruby']),
                'correct_option' => '2',
                'category' => 'Coding',
            ],
            [
                'question' => 'What does CSS stand for?',
                'options' => json_encode(['Computer Style System', 'Cascading Style Sheets', 'Creative Style Syntax', 'Custom Style Syntax']),
                'correct_option' => '1',
                'category' => 'Coding',
            ],
            [
                'question' => 'Which company developed Java?',
                'options' => json_encode(['Microsoft', 'Sun Microsystems', 'Apple', 'Google']),
                'correct_option' => '1',
                'category' => 'Coding',
            ],
            [
                'question' => 'Which of the following is used to style HTML elements?',
                'options' => json_encode(['HTML', 'CSS', 'PHP', 'SQL']),
                'correct_option' => '1',
                'category' => 'Coding',
            ],
            [
                'question' => 'What does PHP stand for?',
                'options' => json_encode(['Personal Hypertext Processor', 'PHP Hypertext Preprocessor', 'Private Hypertext Processor', 'None of the above']),
                'correct_option' => '1',
                'category' => 'Coding',
            ],
            [
                'question' => 'Which language is primarily used for Android app development?',
                'options' => json_encode(['Java', 'Python', 'Ruby', 'Swift']),
                'correct_option' => '0',
                'category' => 'Coding',
            ],
            [
                'question' => 'What does HTML stand for?',
                'options' => json_encode(['HyperText Markup Language', 'HighText Machine Language', 'HyperTool Markup Language', 'HyperText Machine Language']),
                'correct_option' => '0',
                'category' => 'Coding',
            ],
            [
                'question' => 'Which keyword is used to define a function in Python?',
                'options' => json_encode(['func', 'define', 'def', 'lambda']),
                'correct_option' => '2',
                'category' => 'Coding',
            ],
            [
                'question' => 'What is the value of 2 + 2 in binary?',
                'options' => json_encode(['10', '11', '100', '101']),
                'correct_option' => '2',
                'category' => 'Coding',
            ],
            [
                'question' => 'Which programming language is known as the "mother of all languages"?',
                'options' => json_encode(['C', 'COBOL',
                    'Fortran',
                    'Assembly'
                ]),
                'correct_option' => '0',
                'category' => 'Coding',
            ],
            [
                'question' => 'What does CSS stand for?',
                'options' => json_encode(['Cascading Style Sheet', 'Cascading Simple Style', 'Custom Style Sheet', 'Creative Style Syntax']),
                'correct_option' => '0',
                'category' => 'Coding',
            ],
            [
                'question' => 'Which method is used to start a thread in Java?',
                'options' => json_encode(['begin()', 'run()', 'start()', 'init()']),
                'correct_option' => '2',
                'category' => 'Coding',
            ],
            [
                'question' => 'What is the default value of a boolean in Java?',
                'options' => json_encode(['true', 'false', 'null', '0']),
                'correct_option' => '1',
                'category' => 'Coding',
            ],
            [
                'question' => 'What does SQL stand for?',
                'options' => json_encode(['Structured Query Language', 'Simple Query Language', 'System Query Logic', 'Standard Query Language']),
                'correct_option' => '0',
                'category' => 'Coding',
            ],
            [
                'question' => 'Which data structure works on the principle of "Last In, First Out" (LIFO)?',
                'options' => json_encode(['Queue', 'Array', 'Stack', 'List']),
                'correct_option' => '2',
                'category' => 'Coding',
            ],
            [
                'question' => 'Which of the following is not a programming language?',
                'options' => json_encode(['Python', 'JavaScript', 'HTML', 'C#']),
                'correct_option' => '2',
                'category' => 'Coding',
            ],
            [
                'question' => 'What is the output of `console.log(typeof null);` in JavaScript?',
                'options' => json_encode(['"null"', '"undefined"','"number"', '"object"']),
                'correct_option' => '3',
                'category' => 'Coding',
            ],
            [
                'question' => 'What does the `git pull` command do?',
                'options' => json_encode(['Fetches changes and merges them', 'Saves changes to the repository', 'Removes files', 'Clones a repository']),
                'correct_option' => '0',
                'category' => 'Coding',
            ],
            [
                'question' => 'What does the term "closure" refer to in JavaScript?',
                'options' => json_encode(['An inner function with access to an outer function\'s scope', 'A private variable', 'A callback function', 'A global variable']),
                'correct_option' => '0',
                'category' => 'Coding',
            ],
            [
                'question' => 'Which language is used for web development on the backend?',
                'options' => json_encode(['HTML', 'CSS', 'PHP', 'Bootstrap']),
                'correct_option' => '2',
                'category' => 'Coding',
            ],
            [
                'question' => 'Which of these is a frontend framework?',
                'options' => json_encode(['Django', 'Laravel','Flask', 'React']),
                'correct_option' => '3',
                'category' => 'Coding',
            ],
            [
                'question' => 'What does the `isNaN()` function check in JavaScript?',
                'options' => json_encode(['If a value is null', 'If a value is not a number', 'If a variable is undefined', 'If a variable is empty']),
                'correct_option' => '1',
                'category' => 'Coding',
            ],
            [
                'question' => 'Which of these is a NoSQL database?',
                'options' => json_encode(['MySQL', 'MongoDB', 'PostgreSQL', 'SQLite']),
                'correct_option' => '1',
                'category' => 'Coding',
            ],
            [
                'question' => 'Which HTTP method is used to create a resource?',
                'options' => json_encode(['GET', 'POST', 'PUT', 'DELETE']),
                'correct_option' => '1',
                'category' => 'Coding',
            ],
            [
                'question' => 'What is the purpose of the `return` keyword in Python?',
                'options' => json_encode(['End a loop',
                    'End a function',
                    'Pass an error',
                    'Return a value from a function'
                ]),
                'correct_option' => '3',
                'category' => 'Coding',
            ],
            [
                'question' => 'Which symbol is used to start a comment in Python?',
                'options' => json_encode(['#', '//', '/*', '<!--']),
                'correct_option' => '0',
                'category' => 'Coding',
            ],
            [
                'question' => 'Which operator is used for string concatenation in JavaScript?',
                'options' => json_encode(['+', '.', '&', '*']),
                'correct_option' => '0',
                'category' => 'Coding',
            ],
            [
                'question' => 'What is the file extension for Python scripts?',
                'options' => json_encode(['.java', '.php','.js', '.py']),
                'correct_option' => '3',
                'category' => 'Coding',
            ],
            [
                'question' => 'What is a constructor in object-oriented programming?',
                'options' => json_encode(['A method for creating objects', 'A data structure', 'A function without return', 'A static method']),
                'correct_option' => '0',
                'category' => 'Coding',
            ],
            [
                'question' => 'What does the `pip` command do in Python?',
                'options' => json_encode(['Runs Python code', 'Installs Python packages', 'Creates virtual environments', 'Builds Python executables']),
                'correct_option' => '1',
                'category' => 'Coding',
            ],
            [
                'question' => 'Which method is used to add an element to the end of an array in JavaScript?',
                'options' => json_encode(['push()', 'append()', 'add()', 'concat()']),
                'correct_option' => '0',
                'category' => 'Coding',
            ],
            [
                'question' => 'Which language is primarily used for iOS development?',
                'options' => json_encode(['Swift', 'Kotlin', 'Java', 'C#']),
                'correct_option' => '0',
                'category' => 'Coding',
            ],
            [
                'question' => 'What does the `len()` function in Python return?',
                'options' => json_encode(['Length of an array', 'Number of characters in a string', 'Both', 'None']),
                'correct_option' => '2',
                'category' => 'Coding',
            ],
            [
                'question' => 'Which of the following is not a database query language?',
                'options' => json_encode(['SQL', 'SPARQL', 'Gremlin', 'MongoDB']),
                'correct_option' => '3',
                'category' => 'Coding',
            ],
            [
                'question' => 'Which of the following is not a looping construct?',
                'options' => json_encode(['for', 'while', 'do-while', 'if']),
                'correct_option' => '3',
                'category' => 'Coding',
            ],
            // IQ Test
            [
                'question' => 'If a clock shows 3:15, what is the angle between the hour and the minute hand?',
                'options' => json_encode(['0°', '7.5°', '90°', '97.5°']),
                'correct_option' => '1',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'What comes next in the series: 5, 10, 20, 40, ?',
                'options' => json_encode(['60', '80', '100', '70']),
                'correct_option' => '1',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'What is the next number in the series: 1, 1, 2, 3, 5, 8, ?',
                'options' => json_encode(['11', '12', '13', '21']),
                'correct_option' => '1',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'If a train travels at 80 km/h for 3 hours, how far will it go?',
                'options' => json_encode(['200 km', '240 km', '180 km', '300 km']),
                'correct_option' => '1',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'Which word does not belong in the group: Apple, Banana, Cherry, Carrot?',
                'options' => json_encode(['Apple', 'Banana', 'Cherry', 'Carrot']),
                'correct_option' => '3',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'What comes next in the sequence: 2, 4, 8, 16, ?',
                'options' => json_encode(['24', '30', '32', '40']),
                'correct_option' => '2',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'If a triangle has angles of 90°, 45°, and 45°, what type of triangle is it?',
                'options' => json_encode(['Equilateral', 'Isosceles', 'Scalene', 'Obtuse']),
                'correct_option' => '1',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'Find the odd one out: 3, 5, 7, 9, 11.',
                'options' => json_encode(['5', '7', '9', '11']),
                'correct_option' => '2',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'What is 25% of 200?',
                'options' => json_encode(['25', '50', '75', '100']),
                'correct_option' => '1',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'If a clock shows 3:15, what angle is formed by the hour and minute hands?',
                'options' => json_encode(['90°', '97.5°', '105°', '112.5°']),
                'correct_option' => '1',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'Which number completes the pattern? 5, 11, 23, 47, ?',
                'options' => json_encode(['95', '96', '99', '103']),
                'correct_option' => '3',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'Which word does not belong to the group: Apple, Banana, Carrot, Grape?',
                'options' => json_encode(['Apple', 'Banana', 'Carrot', 'Grape']),
                'correct_option' => '2',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'What comes next in the series: 1, 4, 9, 16, ?',
                'options' => json_encode(['20', '24', '25', '30']),
                'correct_option' => '2',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'If you rearrange the letters "EAT", you get a:',
                'options' => json_encode(['Vegetable', 'Animal', 'Food', 'Place']),
                'correct_option' => '2',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'Which number is a multiple of both 3 and 5?',
                'options' => json_encode(['10', '15', '20', '25']),
                'correct_option' => '1',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'A man walks 5 km north, then 3 km east, and finally 5 km south. How far is he from his starting point?',
                'options' => json_encode(['2 km', '3 km', '4 km', '5 km']),
                'correct_option' => '1',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'Which shape has the most sides?',
                'options' => json_encode(['Hexagon', 'Octagon', 'Pentagon', 'Decagon']),
                'correct_option' => '3',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'What is the next prime number after 13?',
                'options' => json_encode(['15', '17', '19', '21']),
                'correct_option' => '1',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'Which number is the smallest: 0.1, 0.01, 0.001, 0.0001?',
                'options' => json_encode(['0.1', '0.01', '0.001', '0.0001']),
                'correct_option' => '3',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'Which figure does not belong to the group?',
                'options' => json_encode(['Circle', 'Triangle', 'Square', 'Sphere']),
                'correct_option' => '3',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'If 5x = 20, what is x?',
                'options' => json_encode(['3', '4', '5', '6']),
                'correct_option' => '1',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'Find the missing number: 2, 6, 12, 20, ?',
                'options' => json_encode(['28', '30', '32', '36']),
                'correct_option' => '0',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'What is half of 0.5?',
                'options' => json_encode(['0.05', '0.1', '0.25', '0.5']),
                'correct_option' => '2',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'If a train travels 60 km in 1 hour, how far will it travel in 2.5 hours?',
                'options' => json_encode(['100 km', '120 km', '150 km', '160 km']),
                'correct_option' => '2',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'What is 15% of 200?',
                'options' => json_encode(['20', '25', '30', '35']),
                'correct_option' => '2',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'What comes next in the pattern: A, C, F, J, ?',
                'options' => json_encode(['K', 'L', 'M', 'N']),
                'correct_option' => '3',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'If you double 10 and add 5, what do you get?',
                'options' => json_encode(['15', '20', '25', '30']),
                'correct_option' => '2',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'What is the largest two-digit prime number?',
                'options' => json_encode(['89', '97', '99', '101']),
                'correct_option' => '1',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'If a car uses 8 liters of fuel to travel 100 km, how much fuel will it use for 250 km?',
                'options' => json_encode(['18 liters', '20 liters', '25 liters', '30 liters']),
                'correct_option' => '1',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'What comes next in the series: 2, 3, 5, 8, ?',
                'options' => json_encode(['11', '12', '13', '15']),
                'correct_option' => '1',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'Which is the odd one out: Lion, Tiger, Leopard, Whale?',
                'options' => json_encode(['Lion', 'Tiger', 'Leopard', 'Whale']),
                'correct_option' => '3',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'What comes next: 1, 4, 9, 16, ?',
                'options' => json_encode(['20', '24', '25', '30']),
                'correct_option' => '2',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'What is the sum of angles in a triangle?',
                'options' => json_encode(['90°', '120°', '180°', '360°']),
                'correct_option' => '2',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'What is the next letter in the pattern: B, D, G, K, ?',
                'options' => json_encode(['M', 'N', 'O', 'P']),
                'correct_option' => '0',
                'category' => 'IQ Test',
            ],
            [
                'question' => 'What is 12 squared?',
                'options' => json_encode(['122', '124',
                    '144',
                    '154'
                ]),
                'correct_option' => '2',
                'category' => 'IQ Test',
            ],
            // Pokemon
            [
                'question' => 'Which Pokémon is a fire-type?',
                'options' => json_encode(['Squirtle', 'Bulbasaur', 'Charmander', 'Pikachu']),
                'correct_option' => '2',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'What level does Magikarp evolve into Gyarados?',
                'options' => json_encode(['20', '15', '30', '25']),
                'correct_option' => '0',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'Which Pokémon is known as the "Legendary Bird of Fire"?',
                'options' => json_encode(['Zapdos', 'Moltres', 'Articuno', 'Ho-Oh']),
                'correct_option' => '1',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'Which type is not super effective against Dragon?',
                'options' => json_encode(['Dragon', 'Ice', 'Fairy', 'Fire']),
                'correct_option' => '3',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'What type of Pokémon is Lapras?',
                'options' => json_encode(['Water', 'Ice', 'Water/Ice', 'Dragon']),
                'correct_option' => '2',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'What is the name of the first Pokémon in the National Pokédex?',
                'options' => json_encode(['Bulbasaur', 'Charmander', 'Pikachu', 'Squirtle']),
                'correct_option' => '0',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'Which type is super effective against Fire?',
                'options' => json_encode(['Water', 'Electric', 'Psychic', 'Bug']),
                'correct_option' => '0',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'What is Pikachu’s evolved form?',
                'options' => json_encode(['Pichu', 'Raichu', 'Jolteon', 'Electivire']),
                'correct_option' => '0',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'Which Pokémon is known as the "Fire Lizard"?',
                'options' => json_encode(['Charizard', 'Magmar', 'Charmander', 'Arcanine']),
                'correct_option' => '3',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'What item is used to evolve Eevee into Vaporeon?',
                'options' => json_encode(['Water Stone', 'Thunder Stone', 'Leaf Stone', 'Moon Stone']),
                'correct_option' => '0',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'Which Legendary Pokémon is associated with the moon?',
                'options' => json_encode(['Solgaleo', 'Lunala', 'Necrozma', 'Dialga']),
                'correct_option' => '1',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'What type of Pokémon is Togepi?',
                'options' => json_encode(['Psychic', 'Fairy', 'Normal', 'Flying']),
                'correct_option' => '1',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'What is the name of Ash’s first rival in the Pokémon series?',
                'options' => json_encode(['Brock', 'Misty', 'James', 'Gary']),
                'correct_option' => '3',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'Which Pokémon is known as the "King of the Sea"?',
                'options' => json_encode(['Gyarados', 'Lapras', 'Kingdra','Kyogre']),
                'correct_option' => '3',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'What type of Pokémon is weak to Electric?',
                'options' => json_encode(['Rock', 'Grass', 'Flying', 'Steel']),
                'correct_option' => '2',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'Which Pokémon is known as the "Aura Pokémon"?',
                'options' => json_encode(['Lucario', 'Gallade', 'Mewtwo', 'Gardevoir']),
                'correct_option' => '0',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'Which Pokémon evolves into Gardevoir?',
                'options' => json_encode(['Ralts', 'Gallade','Mime Jr.', 'Kirlia']),
                'correct_option' => '3',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'What is the highest level a Pokémon can reach in Pokémon Go?',
                'options' => json_encode(['50', '100', '99', '150']),
                'correct_option' => '0',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'What is the pre-evolution of Snorlax?',
                'options' => json_encode(['Laxkin', 'Pillowkin', 'Munchlax', 'None']),
                'correct_option' => '2',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'Which Pokémon is known for its ability "Intimidate"?',
                'options' => json_encode(['Arcanine', 'Salamence', 'Gyarados', 'All of these']),
                'correct_option' => '2',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'What is the name of the region in Pokémon Sun and Moon?',
                'options' => json_encode(['Kalos', 'Sinnoh','Unova', 'Alola']),
                'correct_option' => '3',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'Which Pokémon is known as the "Mouse Pokémon"?',
                'options' => json_encode(['Pikachu', 'Rattata', 'Sandslash', 'Eevee']),
                'correct_option' => '0',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'What is the evolution of Magikarp?',
                'options' => json_encode(['Seaking', 'Gyarados', 'Milotic', 'Sharpedo']),
                'correct_option' => '1',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'Which type combination is super effective against Dragon?',
                'options' => json_encode(['Fairy and Ice', 'Steel and Fire', 'Dark and Psychic', 'Rock and Fighting']),
                'correct_option' => '0',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'What is the signature move of Pikachu?',
                'options' => json_encode(['Thunderbolt', 'Spark', 'Quick Attack', 'Volt Tackle']),
                'correct_option' => '3',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'What is the main character’s name in the Pokémon series?',
                'options' => json_encode(['Ash', 'Red','Blue', 'Gary']),
                'correct_option' => '0',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'Which Pokémon is the mascot of Pokémon Ruby?',
                'options' => json_encode(['Groudon', 'Pikachu', 'Rayquaza', 'Latios']),
                'correct_option' => '0',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'Which Pokémon is known for singing and putting others to sleep?',
                'options' => json_encode(['Clefairy', 'Wigglytuff', 'Lilligant','Jigglypuff']),
                'correct_option' => '3',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'Which Pokémon can evolve using a Thunder Stone?',
                'options' => json_encode(['Pikachu', 'Eevee', 'Both', 'Neither']),
                'correct_option' => '2',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'What type is Togekiss?',
                'options' => json_encode(['Fairy/Flying', 'Normal/Flying', 'Psychic/Flying', 'Fairy/Steel']),
                'correct_option' => '0',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'What type of Poké Ball is most effective on Legendary Pokémon?',
                'options' => json_encode(['Ultra Ball', 'Heavy Ball', 'Timer Ball', 'Quick Ball']),
                'correct_option' => '1',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'What is the first gym leader’s name in the Kanto region?',
                'options' => json_encode(['Misty', 'Lt. Surge', 'Sabrina', 'Brock']),
                'correct_option' => '3',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'Which Pokémon evolves from Eevee using a Leaf Stone?',
                'options' => json_encode(['Leafeon', 'Glaceon', 'Sylveon', 'Espeon']),
                'correct_option' => '0',
                'category' => 'Pokemon',
            ],
            [
                'question' => 'What Pokémon is known as the "Time Travel Pokémon"?',
                'options' => json_encode([ 'Dialga', 'Celebi', 'Palkia', 'Jirachi']),
                'correct_option' => '1',
                'category' => 'Pokemon',
            ],
        ];


        foreach ($questions as $question) {
            DB::table('questions')->insert([
                'question' => $question['question'],
                'options' => $question['options'],
                'correct_option' => $question['correct_option'],
                'category' => $question['category'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
